<?php

// Global entries for the <html> tag
define('HTML_PARAMS','dir="LTR" lang="de"');

// charset for web pages and emails
define('CHARSET', 'utf-8');

// Seitentitel
define('TEXT_LICENCING','Lizenzierung und Copyright-Hinweise');
define('TEXT_GNU','osConcert ist lizenziert unter den Bedingungen der GNU General Public License (GPL) Version 2');
define('TEXT_COPYR','Dieses Thema unterliegt dem Copyright von osconcert.com');
define('TEXT_AGREE','Ich bin mit den Lizenzbedingungen einverstanden');
define('TEXT_INSTALL','Installieren');
define('TEXT_OPEN','Installationsanleitung öffnen');
define('TEXT_ABOUT','osConcert ist angepasst, um <strong>Online Sitzplatzreservierung für das Theater</strong> anzubieten');
define('TEXT_UPGRADE','Upgrade');
define('TEXT_CT','Kompatibilitätstest');
define('TEXT_COMPAT','Kompatibilitätstest für die Installation');
define('TEXT_IO','Installationsoptionen');
define('TEXT_DI','Datenbankimport');
define('TEXT_TC','Testverbindung');
define('TEXT_CUSTOM','Bitte passen Sie die neue Installation mit den folgenden Optionen an:');
define('TEXT_IMPORT','Katalogdatenbank importieren:');
define('TEXT_INSTALL_DB','Installieren Sie die Datenbank und fügen Sie die Beispieldaten hinzu.'); 
define('TEXT_IMPORT','Importieren Sie die erforderlichen Daten der Datenbankstruktur und einige Beispieldaten. (erforderlich für Erstinstallationen)');
define('TEXT_ITB','Die Datenbank installieren');
define('TEXT_CONFIG','Konfiguration');
define('TEXT_AC','Automatische Konfiguration:');
define('TEXT_SAVE_CONFIG','Wenn Sie dieses Kästchen ankreuzen, werden alle während des Installationsvorgangs eingegebenen Daten in den entsprechenden Konfigurationsdateien auf dem Server gespeichert.');
define('TEXT_SCV','Konfigurationswerte speichern');
define('TEXT_CANCEL','Abbrechen');
define('TEXT_CONTINUE','Fortsetzen');
define('TEXT_UNSUCCESSFUL','Eine Testverbindung zur Datenbank war nicht erfolgreich.');
define('TEXT_INSTALLATION','Installation');
define('TEXT_NEW','Neue Installation');
define('TEXT_SC','Server-Fähigkeiten');
define('TEXT_PHP','PHP-Version');
define('TEXT_SETTINGS','PHP-Einstellungen');
define('TEXT_DB1','Datenbank');
define('TEXT_THE_ERROR','Die zurückgegebene Fehlermeldung lautet:');
define('TEXT_REVIEW','Bitte klicken Sie auf die Schaltfläche <i>Zurück</i>, um Ihre Datenbankserver-Einstellungen zu überprüfen.');
define('TEXT_REQUIRE','Wenn Sie Hilfe bei den Einstellungen Ihres Datenbankservers benötigen, wenden Sie sich bitte an Ihr Hosting-Unternehmen.');
define('TEXT_SUCCESS','Eine Testverbindung zur Datenbank wurde erfolgreich hergestellt.');
define('TEXT_UNSUCCESS','Ein Test der Verbindung zur Datenbank war <font color="#AB212E">nicht erfolgreich.</font>
.');
define('TEXT_PLEASE_CONTINUE','Bitte setzen Sie den Installationsprozess fort, um den Datenbankimport durchzuführen.');
define('TEXT_BACKUP','Bitte machen Sie wichtige Backups, wenn ein Upgrade der Datenbank durchgeführt wird.');
define('TEXT_IMPORTANT','Es ist wichtig, dass dieser Vorgang nicht unterbrochen wird, da sonst die Datenbank beschädigt werden könnte.');
define('TEXT_FILES','Die zu importierenden Dateien müssen sich befinden unter:');
define('TEXT_DB_UPGRADE','Ein Datenbank-Upgrade ist für Ihre osConcert-Installation verfügbar.');
define('TEXT_CONSIDER','Bitte denken Sie daran, eine Datenbanksicherung zu erstellen, bevor Sie fortfahren.');

define('TEXT_LOCATED','Die zu importierenden Dateien müssen sich befinden in:');
define('TEXT_LOCATED2','Die folgenden Dateien wurden gefunden und werden installiert:');
define('TEXT_UPTODATE','Die vorhandene osConcert-Datenbank scheint auf dem neuesten Stand zu sein.');
define('TEXT_REINSTALL','Möchten Sie die Datenbank neu installieren, wobei alle vorhandenen Daten gelöscht werden?');
define('TEXT_YES','Ja');
define('TEXT_NO','Nein');
define('TEXT_PROCEED','Klicken Sie auf Weiter, um fortzufahren');
define('TEXT_ENTER','Bitte geben Sie die Informationen zum Datenbankserver ein:');
define('TEXT_DBS','Datenbank-Server:');
define('TEXT_SERVER','Der Datenbankserver kann in Form eines Hostnamens wie db1.myserver.com oder als IP-Adresse wie 192.168.0.1 angegeben werden');
define('TEXT_HOSTNAME','Hostname oder IP-Adresse des Datenbankservers');
define('TEXT_USERNAME','Benutzername:');
define('TEXT_DB','Datenbank-Benutzername');
define('TEXT_USERNAME_USED','Der für die Verbindung zum Datenbankserver verwendete Benutzername. Ein Beispiel-Benutzername ist \'mysql_10\'.\n \n Hinweis: Erstellungs- und Löschberechtigungen <b>sind nicht erforderlich</b> für die allgemeine Verwendung von osConcert.');

define('TEXT_PASSWORD','Passwort:');
define('TEXT_USER','Das Passwort wird zusammen mit dem Benutzernamen verwendet und bildet das Datenbank-Benutzerkonto.');
define('TEXT_DB_PASSWORD','Datenbank-Passwort');
define('TEXT_DB_NAME','Datenbankname:');
define('TEXT_DB_NAME_DESC','Die Datenbank, die zur Speicherung der Daten verwendet wird. Ein Beispiel für einen Datenbanknamen ist \'osconcert\'.');
define('TEXT_DB_NAME2','Datenbankname');
define('TEXT_SS','Sitzungsspeicher:');
define('TEXT_NOTE_SECURITY','Hinweis: Aufgrund von Sicherheitsaspekten wird die Speicherung von Datenbanksitzungen für gemeinsam genutzte Server empfohlen.');
define('TEXT_STORE_USER','Speicherung von Benutzersitzungsdaten in der Datenbank.');
define('TEXT_DB_UNSUCCESFUL','Der Datenbankimport war nicht erfolgreich.');
define('TEXT_SQL_FILE','Sql-Datei:');
define('TEXT_DB_SUCCESSFULL','Der Datenbankimport war <font color=#117a8b>Erfolgreich.</font>');

define('TEXT_HOWEVER','Bei der Ausführung des Sql-Befehls Create View ist jedoch ein Fehler aufgetreten <br>- bitte versuchen Sie, diesen manuell über phpMyAdmin oder ähnlich auszuführen');
define('TEXT_FAILED','Benutzerdefiniertes Upgrade fehlgeschlagen');
define('TEXT_CONTACT_SUPPLIER','Bitte kontaktieren Sie Ihren Software-Lieferanten');
define('TEXT_CUSTOM','Es scheint ein benutzerdefiniertes Upgrade für Ihre Datenbank verfügbar zu sein.');
define('TEXT_CLICK_UPGRADE','Klicken Sie auf Upgrade, um es zu installieren oder Weiter, um diesen Schritt zu überspringen');
define('TEXT_SKIP','Überspringen');
define('TEXT_WAIT','Bitte warten Sie einen Moment');
define('TEXT_SERVER','Server-Konfiguration');
define('TEXT_SSC','Sichere Serverkonfiguration');
define('TEXT_DC','Datenbank-Konfiguration');
define('TEXT_CD','Konfiguration abgeschlossen');
define('TEXT_ENTER2','Bitte geben Sie die Webserver-Informationen ein:');
define('TEXT_WWW_ADDRESS','WWW Address:');
define('TEXT_FULL_ADDRESS','Die vollständige Adresse der Website des Online-Shops');
define('TEXT_WEB_ADDRESS','Die Webadresse zum Online-Shop zum Beispiel <i>http://www.my-server.com/osconcert/</i>');
define('TEXT_WRD','Webserver-Stammverzeichnis:');
define('TEXT_DIRECTORY','Das Verzeichnis, in dem osConcert auf dem Server installiert ist, zum Beispiel <i>/home/myname/public_html/osconcert/</i>');
define('TEXT_PATH','Der Serverpfad zum Online-Store');
define('TEXT_HTTP_COOKIE','HTTP Cookie Domain:');
define('TEXT_TLD','Die vollständige oder Top-Level-Domain, in der die Cookies gespeichert werden, zum Beispiel <i>.mein-server.com</i>');
define('TEXT_COOKIE_DOMAIN','Die Domain, in der Cookies gespeichert werden sollen');
define('TEXT_HTTP_PATH','HTTP-Cookie-Pfad:');
define('TEXT_EXAMPLE','Die Webadresse, auf die das Cookie beschränkt werden soll, zum Beispiel <i>/catalog/</i>');
define('TEXT_PTSC','Der Pfad, unter dem Cookies gespeichert werden sollen');
define('TEXT_HOMEPAGE','Startseite Link:');
define('TEXT_HOMEURL','Der Home-Url-Pfad zum Beispiel <i>http://www.yoursite.com</i>');
define('TEXT_HOMELINK','Home Link');
define('TEXT_SSL','Aktiviere SSL-Verbindungen:');
define('TEXT_ENABLESSL','Aktivieren Sie sichere SSL/HTTPS-Verbindungen (erfordert ein auf dem Webserver installiertes Sicherheitszertifikat)');
define('TEXT_ENABLESSL2','Sichere SSL-/HTTPS-Verbindungen aktivieren');
define('TEXT_ADMIN_NAME','Name des Verwaltungsverzeichnisses:');
define('TEXT_THIS_ADMIN','Dies ist das Verzeichnis, in dem der Administrationsbereich installiert wird. Sie sollten dies aus Sicherheitsgründen ändern.');
define('TEXT_THIS','Dies ist das Verzeichnis, in dem der Administrationsbereich installiert wird.<br>BITTE ÄNDERN SIE DIESES IN ETWAS, DAS SCHWIERIGER ZU FINDEN IST');
define('TEXT_ENTER3','Bitte geben Sie die Informationen zum sicheren Webserver ein:');
define('TEXT_SECURE_CD','Sichere Cookie-Domäne:');
define('TEXT_SECURE_WWW','Sichere WWW-Adresse:');
define('TEXT_HTTPS_COOKIE','HTTPS-Cookie-Domäne:');
define('TEXT_STLD','Die sichere Web-Adresse des Online-Shops, zum Beispiel <i>https://ssl.my-hosting-company.com/osconcert/</i>');
define('TEXT_SCOOKIE_DOMAIN','Die sichere Domain, in der Cookies gespeichert werden');
define('TEXT_HTTPS_PATH','Sicherer Cookie-Pfad:');
define('TEXT_SECURE_WEB','Die Webadresse des sicheren Servers, auf den das Cookie beschränkt werden soll, zum Beispiel <i>/mein_name/katalog/</i>');
define('TEXT_SECURE_FULL','Die vollständige Website-Adresse des Online-Shops auf dem sicheren Server');
define('TEXT_SECURE_FULLTLD','Die vollständige oder Top-Level-Domain des sicheren Servers, auf dem die Cookies gespeichert werden, zum Beispiel <i>ssl.mein-hosting-unternehmen.com</i>');
define('TEXT_HTTPS_DOMAIN','Die sichere Domäne, in der Cookies gespeichert werden');
define('TEXT_SECURE_PATH','Der sichere Pfad, unter dem Cookies gespeichert werden sollen');
define('TEXT_BACK','Bitte klicken Sie auf die Schaltfläche <i>Back</i>, um Ihre Datenbankserver-Einstellungen zu überprüfen.');
define('TEXT_HELP','Wenn Sie Hilfe zu den Einstellungen Ihres Datenbankservers benötigen, wenden Sie sich bitte an Ihr Hosting-Unternehmen.');
define('TEXT_ERROR2','Der folgende Fehler ist aufgetreten:');
define('TEXT_NOT_EXIST','Die Konfigurationsdateien existieren nicht oder die Berechtigungsstufen sind nicht gesetzt.');
define('TEXT_PERFORM','Bitte führen Sie die folgenden Aktionen aus:');
define('TEXT_SUCCESSFUL2','Die Konfiguration war <font color=#117a8b>Erfolgreich</font>');
define('TEXT_ADMIN','Admin');
define('TEXT_CATALOGS','Kataloge');
define('TEXT_IMPORT_SP','Importiere die osConcert Beispielhafte Daten');
define('TEXT_IMPORT_SP2','Importieren der osConcert Design-Modus Dateien');
define('TEXT_NOTFOUND','osconcert_data.sql not found in install folder');
define('TEXT_CHANGE','Bitte ändern Sie die Login-Einstellungen für das Administrationstool');
define('TEXT_FINISHED','Installation abgeschlossen');
define('TEXT_SUCCESSFUL3','Die Installation war <strong>Erfolgreich</strong>');
define('TEXT_ADMIN_LOGIN_SETTINGS','Die Login-Einstellungen für das Administrationstool wurden <strong>erfolgreich</strong> gesetzt');
define('TEXT_TOOL','Bitte ändern Sie die Login-Einstellungen für das Administrations-Tool.');
define('TEXT_EMAIL','E-Mail Adresse:');
define('TEXT_CONFIRM','Passwortbestätigung:');
define('TEXT_SQLERROR','MySQLi-Fehler - weitere Maßnahmen erforderlich');
define('TEXT_VIEW','Während die Datenbank erfolgreich installiert wurde, schlug der Versuch, automatisch einen MySQL Create View-Befehl auszuführen, mit diesem Fehler fehl:');
define('TEXT_MANUALLY','Sie müssen die folgende MySQL-Abfrage manuell ausführen, entweder über Ihr Hosting-Kontrollpanel oder, in einigen Fällen, indem Sie Ihr Hosting-Unternehmen darum bitten:');
define('TEXT_AFTER','Nach der Installation das Installationsverzeichnis entfernen');
define('TEXT_STILL_EXISTS','install <b>Verzeichnis existiert noch</b>');
define('TEXT_DELETED','Aus Sicherheitsgründen sollte dies gelöscht werden.');
define('TEXT_WRITABLE',' <strong>ist beschreibbar. Bitte ändern Sie dies nach der Installation.</strong><br>');
define('TEXT_CDS','Config Verzeichnis Sicherheit');
define('TEXT_FRONT_END','Frontend');
define('TEXT_ADMINISTRATION','Verwaltung');
define('TEXT_CONF_OSC','osConcert konfigurieren');
define('TEXT_COMPLETE','Installation abgeschlossen');
define('TEXT_LOGIN_SETTINGS','Die Login-Einstellungen für das Administrationstool sind <b>Benutzername</b>: webmaster@osconcert.com');
define('TEXT_PASSWORD_SETTINGS','&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Passwort</b>:user@123@go ');

//Übersetzt mit www.DeepL.com/Translator (kostenlose Version)
?>